import "@/app/globals.css";

import type { Metadata } from "next";
import { Abril_Fatface, Alata } from "next/font/google";

import { AppQueryClientProvider } from "@/shared/providers/query-client-provider";
import { Toaster } from "@/shared/ui/sonner";
import { TooltipProvider } from "@/shared/ui/tooltip";

const alata = Alata({
  variable: "--font-alata",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
});

const abrilFatface = Abril_Fatface({
  variable: "--font-abril",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alata.variable} ${abrilFatface.variable} antialiased`}
        suppressHydrationWarning
      >
        <AppQueryClientProvider>
          <TooltipProvider>
            {children}
            <Toaster />
          </TooltipProvider>
        </AppQueryClientProvider>
      </body>
    </html>
  );
}
